name: macOS
on: [push]
jobs:
  mac_os_build:
    runs-on: macos-latest
    env:
      DEVELOPER_DIR: /Applications/Xcode_13.0.app/Contents/Developer
      CODECOV_TOKEN: 4dcab976-dc00-4d0a-af2c-ff675655a733
    steps:
    - uses: actions/checkout@v1
    - name: Build
      run: swift build
    - name: Test
      run: swift test --enable-test-discovery --enable-code-coverage
    - name: Codecov
      run: |
        xcrun llvm-cov export -format="lcov" .build/debug/SwiftCoroutinePackageTests.xctest/Contents/MacOS/SwiftCoroutinePackageTests -instr-profile .build/debug/codecov/default.profdata --ignore-filename-regex "Tests/.*" > info.lcov
        bash <(curl -s https://codecov.io/bash)
